dist: xenial
language: python
sudo: false

python:
  - 3.7
  - 3.8

services:
  - postgresql


addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.4

env:
  - DJANGO=2.1
  - DJANGO=2.2

install:
  - pip install tox codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}" -- py.test tests -v

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
