# Generated by Django 4.0 on 2021-12-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterModelTable(
            name='locationremaphistory',
            table=None,
        ),
    ]
