# Generated by Django 4.0 on 2022-02-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_locations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GatewayType',
        ),
    ]
