# Generated by Django 2.0.7 on 2019-01-10 23:36

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20181206_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartodbtable',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now,
                                                      editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now,
                                                           editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='gatewaytype',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now,
                                                      editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='gatewaytype',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now,
                                                           editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='locationremaphistory',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now,
                                                           editable=False, verbose_name='modified'),
        ),
    ]
