# Generated by Django 2.0.9 on 2019-01-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20190110_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationremaphistory',
            options={'verbose_name': 'Remap history', 'verbose_name_plural': 'Location remap history'},
        ),
    ]
