# Generated by Django 2.0.9 on 2019-01-09 18:37

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models

import unicef_locations.libs


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20190122_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcgisDBTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_url', models.CharField(max_length=512, verbose_name='Service URL')),
                ('service_name', models.CharField(max_length=254, verbose_name='Service Name')),
                ('name_col', models.CharField(default='name', max_length=254, verbose_name='Name Column')),
                ('pcode_col', models.CharField(default='pcode', max_length=254, verbose_name='Pcode Column')),
                ('remap_table_service_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Remap Table Service URL')),
                ('parent_code_col', models.CharField(blank=True, default='', max_length=254, verbose_name='Parent Code Column')),
                ('color', models.CharField(blank=True, default=unicef_locations.libs.get_random_color, max_length=7, verbose_name='Color')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.GatewayType', verbose_name='Location Type')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.ArcgisDBTable', verbose_name='Parent')),
            ],
        ),
    ]
