# Generated by Django 4.0 on 2021-12-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_locations', '0008_auto_20190422_1537'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='locationremaphistory',
                    name='new_location',
                ),
                migrations.RemoveField(
                    model_name='locationremaphistory',
                    name='old_location',
                ),
                migrations.DeleteModel(
                    name='Location',
                ),
                migrations.DeleteModel(
                    name='LocationRemapHistory',
                ),
            ],
            database_operations=[],
        )
    ]
