# Generated by Django 4.0 on 2022-02-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20190422_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartodbtable',
            name='admin_level',
            field=models.SmallIntegerField(default=-1, verbose_name='Admin Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='admin_level_name',
            field=models.CharField(default=-1, max_length=64, verbose_name='Admin Level Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='admin_level',
            field=models.SmallIntegerField(default=-1, verbose_name='Admin Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='admin_level_name',
            field=models.CharField(default=-1, max_length=64, verbose_name='Admin Level Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LocationRemapHistory',
        ),
    ]
