# Generated by Django 4.0 on 2022-02-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20220204_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartodbtable',
            name='location_type',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'p_code')},
        ),
        migrations.RemoveField(
            model_name='location',
            name='gateway',
        ),
    ]
