# Generated by Django 4.0 on 2022-02-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_remove_cartodbtable_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='admin_level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Admin Level'),
        ),
        migrations.AlterField(
            model_name='location',
            name='admin_level_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Admin Level Name'),
        ),
    ]
